# Change these first
owner: coille02
repo: Uptime

sites:
  - name: linegames Web
    url: https://www.line.games
  - name: floor
    url: https://floor.line.games
  - name: uwo sentry
    url: https://sentry22.uwo.line.games
  - name: uwo log
    url: https://es.uwo.line.games/
  - name: uwo apm
    url: https://apm-web.uwo.line.games/
  - name: uwo lua crash
    url: https://titanic.motifgames.in/

status-website:

  cname: board.uwo.line.games
  logoUrl: https://static.line.games/official/image/linegames/logo.png
  name: UWO
  introTitle: "Web Status"
  introMessage: 서비스 상태 모니터링
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
