# Change these first
owner: coille02
repo: upptime

sites:
  - name: linegames Web
    url: https://www.line.games
  - name: floor
    url: https://floor.line.games
  - name: uwo sentry
    url: https://sentry22.uwo.line.games
  - name: pacman  
    url: https://pacman.line.games

status-website:
  theme: light
  cname: board.uwo.line.games
  logoUrl: https://static.line.games/official/image/linegames/logo.png
  name: LineGames
  introTitle: "Web Status"
  introMessage: 서비스 상태 모니터링
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
